//Auth
export const ACCESS_TOKEN = "ACCESS_TOKEN"

//Common
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const GET_APPVERSIONS_FAILED = "GET_APPVERSIONS_FAILED";
export const GET_APPVERSIONS = "GET_APPVERSIONS";
export const CREATE_APPVERSIONS = "CREATE_APPVERSIONS";
export const CREATE_APPVERSIONS_FAILED = "CREATE_APPVERSIONS_FAILED";
export const UPDATE_APPVERSIONS = "UPDATE_APPVERSIONS";
export const UPDATE_APPVERSIONS_FAILED = "UPDATE_APPVERSIONS_FAILED";

//Admin
export const GET_METADATA = "GET_METADATA";
export const GET_METADATA_FAILED = "GET_METADATA_FAILED";
export const GET_ALL_MERCHANTS = "GET_ALL_MERCHANTS";
export const GET_ALL_MERCHANTS_FAILED = "GET_ALL_MERCHANTS_FAILED";
export const GET_ALL_TERMINALS = "GET_ALL_TERMINALS";
export const GET_ALL_TERMINALS_FAILED = "GET_ALL_TERMINALS_FAILED";
export const CREATE_MERCHANTS = "CREATE_MERCHANTS";
export const CREATE_MERCHANTS_FAILED = "CREATE_MERCHANTS_FAILED";
export const UPDATE_MERCHANTS = "UPDATE_MERCHANTS";
export const UPDATE_MERCHANTS_FAILED = "UPDATE_MERCHANTS_FAILED";
export const GET_ALL_MERCHANT_NETWORK_PROFILES = "GET_ALL_MERCHANT_NETWORK_PROFILES";
export const GET_ALL_MERCHANT_NETWORK_PROFILES_FAILED = "GET_ALL_MERCHANT_NETWORK_PROFILES_FAILED";
export const CREATE_TERMINALS = "CREATE_TERMINALS";
export const CREATE_TERMINALS_FAILED = "CREATE_TERMINALS_FAILED";
export const UPDATE_TERMINALS = "UPDATE_TERMINALS";
export const UPDATE_TERMINALS_FAILED = "UPDATE_TERMINALS_FAILED";
export const CREATE_TERMINAL_NETWORKS = "CREATE_TERMINAL_NETWORKS";
export const CREATE_TERMINAL_NETWORKS_FAILED = "CREATE_TERMINAL_NETWORKS_FAILED";
export const UPDATE_TERMINAL_NETWORKS = "UPDATE_TERMINAL_NETWORKS";
export const UPDATE_TERMINAL_NETWORKS_FAILED = "UPDATE_TERMINAL_NETWORKS_FAILED";
export const GET_ALL_TERMINAL_NETWORKS = "GET_ALL_TERMINAL_NETWORKS";
export const GET_ALL_TERMINAL_NETWORKS_FAILED = "GET_ALL_TERMINAL_NETWORKS_FAILED";
export const DELETE_TERMINAL_NETWORKS = "DELETE_TERMINAL_NETWORKS";
export const DELETE_TERMINAL_NETWORKS_FAILED = "DELETE_TERMINAL_NETWORKS_FAILED";
export const DELETE_MERCHANT_NETWORK_PROFILE = "DELETE_MERCHANT_NETWORK_PROFILE";
export const DELETE_MERCHANT_NETWORK_PROFILE_FAILED = "DELETE_MERCHANT_NETWORK_PROFILE_FAILED";

//Payment
export const GET_TRANSACTION_DATA = "GET_TRANSACTION_DATA";
export const GET_TRANSACTION_DATA_FAILED = "GET_TRANSACTION_DATA_FAILED";
export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL";
export const GET_TRANSACTION_DETAIL_FAILED = "GET_TRANSACTION_DETAIL_FAILED";
export const GET_TRANSACTION_SEQUENCE = "GET_TRANSACTION_SEQUENCE";
export const GET_TRANSACTION_SEQUENCEL_FAILED = "GET_TRANSACTION_SEQUENCE_FAILED";
export const MANNUAL_REFUND = "MANNUAL_REFUND";
export const MANNUAL_REFUND_FAILED = "MANNUAL_REFUND_FAILED";

